version: '3.7'

services:

  app:
    restart: always
    build:
      context: .
    ports:
      - "8090:8090"
      - "8080:8080"
      - "8000:8000"
    volumes:
      # - /opt/eurotoken/database:/vol/database
      - ./backend/.local:/vol/database
      - ~/.ssh/eurotoken:/vol/keys

      - ./frontend:/ur

    # environment:
      # - DEBUG=1


